In [ ]:
import numpy as np

In [ ]:
import numpy as np #here we import the numpy

a=np.array([1,2,3]) #here we create the array 
b = a.astype('float32')#herer we convert the datatype to float 32

print(b.dtype) #here we print the b datatype and dtype is function to show the datatype
print(a.ndim) #it show the dimension of array
print(a) #just simply print the array a 
print(b) # just simply print array B
a.shape #it show the shape of the array

float32
1
[1 2 3]
[1. 2. 3.]


(3,)

In [ ]:
# 2D and 3D
b = np.array([[1.0,2.0,3.0],[4,5,6]])#here we create the array 
print(b.ndim) #it show the dimension of array
print(b.dtype) #here we print the b datatype and dtype is function to show the datatype
print(b)# just simply print array B

2
float64
[[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# [value]
# [[a],[b]]
# [[[a],[b]], [[a],[b]]]

print(c.ndim)
print(c.dtype)
print(c)

3
int64
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.array([1,2,3],dtype=float)#specify that the data type should be float

array([1., 2., 3.])

In [ ]:
# np.arange
np.arange(2,11,2)#here it give the value between 2 and 11 at a 2 gap

array([ 2,  4,  6,  8, 10])

In [ ]:
a = np.arange(16).reshape(4, 4)#array with elements from 0 to 15 and reshape it into a 4x4 matrix
b = np.arange(16).reshape(8, 2)#array with elements from 0 to 15 and reshape it into an 8x2 matrix
c = np.arange(16).reshape(4, 2, 2)#array with elements from 0 to 15 and reshape it into a 4x2x2 tensor

print(b)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]


In [ ]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))#here it print zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))#it print the random number

array([[0.38646147, 0.02914786, 0.35392467, 0.38333888],
       [0.97241069, 0.77494205, 0.63629421, 0.57489312],
       [0.287428  , 0.50048915, 0.94175095, 0.19178201]])

In [ ]:
a = np.arange(2,11,2) #array with elements starting from 2 up to (but not including) 11, with a step of 2
b = np.linspace(-10,10,5,dtype=int) #array with 5 evenly spaced values between -10 and 10, with the data type specified as int
print(a)
print(b)

[ 2  4  6  8 10]
[-10  -5   0   5  10]


In [ ]:
np.identity(3)# Make a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a1 = np.arange(12,dtype=np.int32)# Make a list of numbers from 0 to 11
a2 = np.arange(12,dtype=float).reshape(3,4)# Make a list of numbers from 0 to 11, as float
a3 = np.arange(8).reshape(2,2,2)# Make a list of numbers from 0 to 7 and reshape it into 2x2x2

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
print(a1.shape)
a3.ndim

(12,)


3

In [ ]:
# shape
print(a2.shape)# Show the shape
print(a2)# Show the 3x4
print(a3.shape)# Show the shape
a3

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
print(a2.size)# size
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
print(a3.size)# Show the total number
print(a3.itemsize)# Show the size of each item
print(a3)

8
8
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [ ]:
a3.astype(np.int32)# Change the type of numbers

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1** 2 # Square each number in the list a1

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a2 == 15# Check if each number in the 3x4 grid a2 is equal to 15 when it match it print true

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a1 ** a2 #Raise each number in a1 to the power of the corresponding number in a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
a1 = np.random.random((3,3))# Make a 3x3 grid of random numbers
a1 = np.round(a1*100)# Multiply each number by 100 and round it
a1

array([[14., 40., 68.],
       [53., 39., 79.],
       [21., 58., 98.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=1)

array([  9758., 102544., 150822.])

In [ ]:
np.var(a1,axis=1)# mean/median/std/var

array([486.22222222, 274.66666667, 988.66666667])

In [ ]:
np.sin(a1)

array([[ 0.99060736,  0.74511316, -0.89792768],
       [ 0.39592515,  0.96379539, -0.44411267],
       [ 0.83665564,  0.99287265, -0.57338187]])

In [ ]:
a2 = np.arange(12).reshape(3,4)# Make a list of numbers from 0 to 11 and reshape it into a 3x4
a3 = np.arange(12,24).reshape(4,3)# Make a list of numbers from 12 to 23 and reshape it into a 4x3
print(a2)
print()
print(a3)
print()
print(np.dot(a2,a3))# Compute the dot product of a2 and a3
print()
print(a2.dot(a3))# Compute the dot product of a2 and a3
print()
print(a2@a3)# Compute the dot product of a2 and a3 using the @ 
print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]

[[114 120 126]
 [378 400 422]
 [642 680 718]]



In [ ]:
np.exp(a1)# Calculate the exponential (e^x) of each number in the 3x3 grid 

array([[1.20260428e+06, 2.35385267e+17, 3.40427605e+29],
       [1.04137594e+23, 8.65934004e+16, 2.03828107e+34],
       [1.31881573e+09, 1.54553894e+25, 3.63797095e+42]])

In [ ]:
np.ceil(np.random.random((2,3))*100)# Make a 2x3 grid of random numbers Multiply each number by 100 Round each number up to the nearest whole number

array([[84., 58., 56.],
       [65., 14.,  8.]])

In [1]:
a1 = np.arange(10)# Creating a 1-dimensional array with values from 0 to 9
print(a1)
print()
a2 = np.arange(12).reshape(3,4)# Creating a 2-dimensional array with values from 0 to 11 reshape to 3 roe and 4 colummn
print(a2)
a3 = np.arange(8).reshape(2,2,2)# Creating a 3-dimensional array with values from 0 to 7 
print()
a3

NameError: name 'np' is not defined

In [ ]:
a1[0:5]#Selecting elements from index 0 to index 4

array([0, 1, 2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]#Accessing the element at index (1, 0, 1)

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,0:3]#selecting rows from index 0 to 1 & columns from index 0 to 2
 

array([[0, 1, 2],
       [4, 5, 6]])

In [ ]:
a2[1::2,1::2] 

array([[5, 7]])

In [ ]:
a2[1,::3]# Extracting elements from array a2 selecting every third element across all columns

array([4, 7])

In [ ]:
a2[0,:]## Extracting all elements from the first row of array a2

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]# starting from block 2 selecting all rows starting from index 1, and all columns starting from index 1

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
arr=np.arange(1,10,2)#Creating an array elements from 1 to 9, stepping by 2
print("Elements of array: ",arr)
arr1=arr[np.array([4,0,2,-1,-2])]# Using an array as index to retrieve specific elements
print("Indexed Elements of array arr: ",arr1)

Elements of array:  [1 3 5 7 9]
Indexed Elements of array arr:  [9 1 5 9 7]


In [ ]:
#Indexing 2-D array
arr=np.arange(12)# Creating a 1D array with elements from 0 to 11
arr1=arr.reshape(3,4)# Reshaping 'arr' into a 2D array 'arr1' with 3 rows and 4 columns
print("Array arr1:\n",arr1)
print("Element at 0th row and 0th column of arr1 is:",arr1[0,0])
print("Element at 1st row and 2nd column  of arr1 is:",arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at 0th row and 0th column of arr1 is: 0
Element at 1st row and 2nd column  of arr1 is: 6


In [ ]:
arr = np.arange(12)# Creating a 1D array 'arr' with elements from 0 to 11
print(arr)
print("Element at index 6 of an array arr:",arr[6])
print("Element from index 3 to 8 of an array arr:",arr[3:8])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Element at index 6 of an array arr: 6
Element from index 3 to 8 of an array arr: [3 4 5 6 7]


In [ ]:
arr = np.array([[[1,2,3],[3,4,5]],[[5,6,7],[9,10,11]]])# Creating a 3D array
print ("The array is:")
print (arr )
print ('\n')
## Access the last dimension
print("using simple indexing:\n",arr[:,:,0])
print("using ellipsis:\n ",arr[...,0])

The array is:
[[[ 1  2  3]
  [ 3  4  5]]

 [[ 5  6  7]
  [ 9 10 11]]]


using simple indexing:
 [[1 3]
 [5 9]]
using ellipsis:
  [[1 3]
 [5 9]]


In [ ]:
arr = np.array([[11 ,12 ],[13 ,14 ],[15 ,16 ]])# Creating a 2D array
print(arr[[0 ,1 ,2 ],[0 ,0 ,1]])# Accessing specific elements

[11 13 16]


In [ ]:
#Pure integer Indexing
arr=np.array([2,76,34,12,90,32])
print("Original array: ",arr)
adv_arr=np.array([1,3,1,5,2,2,2])
print("Advanced array :",arr[adv_arr])

Original array:  [ 2 76 34 12 90 32]
Advanced array : [76 12 76 32 34 34 34]


In [ ]:
arr = np.array([11,6,41,10,29,50,55,45])
print(arr[arr>35])

[41 50 55 45]


In [ ]:
arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16, 17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])
print(arr)
print("\n")
print("sliced array: \n",arr[1:,0:,:3])

[[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


sliced array: 
 [[[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


In [ ]:
arr = np.array([[[1, 2, 3], [11, 13, 14], [21, 22, 23]],
               [[4, 5, 6], [15, 16, 17], [24, 25, 26]],
               [[7, 8, 9], [18, 19, 20], [27, 28, 29]]])# Creating a 3D array
print(arr)
print("\n")
print("sliced array: \n",arr[1:,0:,:3])# Slicing the array to extract a subset

[[[ 1  2  3]
  [11 13 14]
  [21 22 23]]

 [[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


sliced array: 
 [[[ 4  5  6]
  [15 16 17]
  [24 25 26]]

 [[ 7  8  9]
  [18 19 20]
  [27 28 29]]]


In [ ]:
a1

for i in a1:
  print(i)  # Iterate over each element in a1 and print it

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division